## Diabetes Classification

In [95]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [96]:
# Read the dataset
X_Train = pd.read_csv('Training Data/Diabetes_XTrain.csv')
Y_Train = pd.read_csv('Training Data/Diabetes_YTrain.csv')

In [97]:
X_Train = X_Train.values
Y_Train =Y_Train.values
print(X_Train.shape)
print(Y_Train.shape)

(576, 8)
(576, 1)


In [98]:
# Normalisation  --> Method 1
# ut = np.mean(X_Train,axis=0)
# std_st = np.std(X_Train,axis=0)
# print(ut)
# print(std_st)
# Normalisation --> method 2 Min max scaling
min = np.min(X_Train,axis=0)
max = np.max(X_Train,axis=0)

In [99]:
#
# X_Train =(X_Train - ut)/std_st
X_Train = (X_Train - min)/(max - min)
print(pd.DataFrame(X_Train[:5,:]))

          0         1         2         3         4         5         6  \
0  0.411765  0.844221  0.721311  0.666667  0.431452  0.569300  0.302733   
1  0.470588  0.552764  0.622951  0.000000  0.000000  0.414307  0.067891   
2  0.411765  0.738693  0.622951  0.000000  0.000000  0.587183  0.076430   
3  0.117647  0.502513  0.540984  0.317460  0.120968  0.490313  0.336892   
4  0.235294  0.648241  0.704918  0.317460  0.362903  0.523100  0.065329   

          7  
0  0.316667  
1  0.616667  
2  0.366667  
3  0.116667  
4  0.033333  


In [100]:
Y_Train = Y_Train.reshape((-1,))
print(Y_Train.shape)

(576,)


In [101]:
def dist(x1,x2):
    return np.sqrt(sum((x1-x2)**2))

def knn(X,Y,querypoint,k=5):
    vals = []
    m = X.shape[0]
    for i in range(m):
        d = dist(querypoint,X[i])
        vals.append((d,Y[i]))
    vals = sorted(vals)
    # Nearest k points
    vals = vals[:k]
    vals = np.array(vals,dtype =object)
    new_vals = np.unique(vals[:,1],return_counts=True)

    index = new_vals[1].argmax()
    pred = new_vals[0][index]
    return pred

In [102]:
# Testing the dataset
X_test = pd.read_csv('/Users/apoorvgarg/Downloads/Diabetes_Xtest.csv')

In [103]:
X_test = X_test.values
X_test =(X_test - min)/(max - min)


In [104]:
print(X_test)
n= X_test.shape[0]
print(n)
k =int(np.sqrt(n))
print(k)

[[0.         0.90452261 0.73770492 ... 0.54396423 0.10076857 0.23333333]
 [0.11764706 0.46733668 0.52459016 ... 0.56631893 0.25448335 0.03333333]
 [0.11764706 0.57286432 0.55737705 ... 0.42771982 0.0059778  0.06666667]
 ...
 [0.         0.81407035 0.62295082 ... 0.73919523 0.12211785 0.08333333]
 [0.70588235 0.42211055 0.59016393 ... 0.44262295 0.09350982 0.41666667]
 [0.         0.47236181 0.         ... 0.         0.07600342 0.06666667]]
192
13


In [110]:
ans = []
for test in X_test:
    x = knn(X_Train,Y_Train,test,k=25)
    ans.append(int(x))

In [112]:
df = pd.DataFrame(np.array(ans),columns=["Outcome"])

df.to_csv('Ans_dia5.csv',index=False)